import {SEED,SIMULATION_LABEL,random,createSimulation,totals,filterEvents,validateEvents,normalizeDay} from './simulation.js';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
const CATEGORIES={rescue:'救援',community:'互助',culture:'文化',nature:'自然',accident:'意外',violence:'暴力'};
const format=n=>n===null?'未提供':n.toLocaleString('zh-TW');
const state={day:1,county:'all',categories:Object.keys(CATEGORIES),births:true,deaths:true,news:true,playing:false,speed:2,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
let population,geometry,eventData,simulation,particles=[],last=0,elapsed=0,toastTimer;
const svg=(tag,attrs={},parent)=>{const el=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);if(parent)parent.append(el);return el;};
function text(tag,value,className){const el=document.createElement(tag);el.textContent=value;if(className)el.className=className;return el;}
function link(label,url){const a=text('a',label);a.href=url;a.target='_blank';a.rel='noopener';return a;}
function announce(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2500);}
function readURL(){const q=new URL(location.href).searchParams;state.day=normalizeDay(q.get('day'));state.county=population.counties.some(c=>c.name===q.get('county'))?q.get('county'):'all';if(q.has('categories'))state.categories=q.get('categories').split(',').filter(c=>c in CATEGORIES);else state.categories=Object.keys(CATEGORIES);for(const k of ['births','deaths','news'])state[k]=q.get(k)!=='0';}
function saveURL(){const u=new URL(location.href);u.search='';if(state.day!==1)u.searchParams.set('day',state.day);if(state.county!=='all')u.searchParams.set('county',state.county);if(state.categories.length!==6)u.searchParams.set('categories',state.categories.join(','));for(const k of ['births','deaths','news'])if(!state[k])u.searchParams.set(k,'0');history.pushState(null,'',u);}
function selectCounty(name){state.county=state.county===name?'all':name;saveURL();render();}
function buildMap(){
 for(let y=70;y<740;y+=65)svg('line',{x1:15,x2:700,y1:y,y2:y,stroke:'#72908b','stroke-opacity':'.07'},$('mapGrid'));
 for(let x=25;x<700;x+=65)svg('line',{x1:x,x2:x,y1:50,y2:725,stroke:'#72908b','stroke-opacity':'.07'},$('mapGrid'));
 for(const inset of geometry.insets){const[x,y,w,h]=inset.box;const r=svg('rect',{x,y,width:w,height:h,rx:5,class:'inset-frame',tabindex:0,role:'button','aria-label':`${inset.name}離島插圖，點選篩選`},$('countyPaths'));r.style.cursor='pointer';r.addEventListener('click',()=>selectCounty(inset.name));r.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectCounty(inset.name);}});svg('text',{x:inset.label[0],y:inset.label[1],class:'inset-label'},$('countyLabels')).textContent=`${inset.name} · 插圖`;for(const sub of inset.subInsets||[]){const[a,b,c,d]=sub.box;svg('rect',{x:a,y:b,width:c,height:d,class:'inset-frame'},$('countyPaths'));svg('text',{x:sub.label[0],y:sub.label[1],class:'inset-label','font-size':8},$('countyLabels')).textContent=sub.name;}}
 const labelOffsets={'基隆市':[28,-13],'臺北市':[-18,-20],'新北市':[43,12],'新竹市':[-43,-5],'新竹縣':[3,10],'嘉義市':[-48,0],'嘉義縣':[13,11]};
 for(const f of geometry.features){const p=svg('path',{d:f.path,'fill-rule':'evenodd',class:'county','data-county':f.name,tabindex:0,role:'button','aria-label':`${f.name}，點選查看官方月登記數與新聞`,id:`county-${f.code}`},$('countyPaths'));const title=svg('title',{},p);title.textContent=`${f.name} · 縣市尺度示意`;p.addEventListener('click',()=>selectCounty(f.name));p.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();selectCounty(f.name);}});const clip=svg('clipPath',{id:`clip-${f.code}`},$('map').querySelector('defs'));svg('path',{d:f.path,'fill-rule':'evenodd','clip-rule':'evenodd'},clip);
 if(!f.inset){const[dx,dy]=labelOffsets[f.name]||[0,0];if(dx||dy)svg('line',{x1:f.anchor[0],y1:f.anchor[1],x2:f.anchor[0]+dx,y2:f.anchor[1]+dy,stroke:'#aec5b3','stroke-width':.7,'stroke-opacity':.5},$('countyLabels'));svg('text',{x:f.anchor[0]+dx,y:f.anchor[1]+dy,'text-anchor':'middle',class:'county-label','data-name':f.name},$('countyLabels')).textContent=f.name;}
 const bounds=p.getBBox(),rng=random(`${SEED}:positions:${f.name}`),c=simulation.find(c=>c.name===f.name);for(const type of ['births','deaths']){const count=Math.min(8,Math.max(1,Math.ceil(Math.sqrt(c[type]||0)/6)));for(let i=0;i<count;i++){let pt={x:f.anchor[0],y:f.anchor[1]};for(let n=0;n<120;n++){const candidate=new DOMPoint(bounds.x+rng()*bounds.width,bounds.y+rng()*bounds.height);if(p.isPointInFill(candidate)){pt=candidate;break;}}const circle=svg('circle',{cx:pt.x,cy:pt.y,r:1.5+rng()*1.7,fill:type==='births'?'#e2f2c3':'#ddd1ee',opacity:.5,'clip-path':`url(#clip-${f.code})`},$('particles'));particles.push({circle,county:f.name,type,x:pt.x,y:pt.y,phase:rng()*Math.PI*2,r:1.5+rng()*1.7});}}
 }
}
function filtered(){return simulation.filter(c=>state.county==='all'||c.name===state.county);}
function currentEvents(){return state.news?filterEvents(eventData.events,state):[];}
function renderMarkers(events){$('newsMarkers').replaceChildren();const groups=new Map();for(const e of events){if(!groups.has(e.county))groups.set(e.county,[]);groups.get(e.county).push(e);}for(const[name,list]of groups){const f=geometry.features.find(f=>f.name===name);if(!f)continue;const[x,y]=f.anchor;const g=svg('g',{tabindex:0,role:'button','aria-label':`${name}，${list.length}則真實新聞；縣市示意，非實際位置`},$('newsMarkers'));svg('path',{d:`M${x},${y-9}l8,9 -8,9 -8,-9Z`,class:'news-marker'},g);svg('title',{},g).textContent=`${name}：${list.length} 則真實新聞，縣市位置示意`;const action=()=>{state.county=name;saveURL();render();$('journalTitle').focus({preventScroll:true});$('journalTitle').scrollIntoView({behavior:state.reduced?'instant':'smooth',block:'start'});};g.addEventListener('click',action);g.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();action();}});}}
function renderEvents(events){$('events').replaceChildren();$('eventCount').textContent=`至 8/${state.day} · ${events.length} 則紀事`;if(!events.length){const empty=text('div','', 'empty');empty.append(text('strong',state.news?'這一頁，暫時留白。':'新聞圖層已關閉。'),text('p',state.news?'目前日期與篩選條件下沒有收錄新聞。沒有報導，不代表沒有事情發生。':'打開新聞紀事圖層，即可閱讀有來源的真實事件。'));const button=text('button',state.news?(state.day===31?'查看全台新聞 ↗':'看到月底 ↗'):'顯示新聞紀事','text-button');button.onclick=()=>{if(state.news){if(state.day===31){state.county='all';state.categories=Object.keys(CATEGORIES);}state.day=31;}else state.news=true;saveURL();render();};empty.append(button);$('events').append(empty);return;}
 for(const e of [...events].sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id))){const card=text('article','','event-card');card.id=`event-${e.id}`;const meta=text('div','','event-meta');meta.append(text('span',CATEGORIES[e.category]),text('span',`· ${e.county}`));const date=text('time',e.date.slice(5).replace('-',' / '));date.dateTime=e.date;meta.append(date);card.append(meta,text('h3',e.title),text('p',e.summary));const source=text('div','','source');source.append(link(`${e.sourceName} ↗`,e.url),text('span','真實新聞'));card.append(source,text('p',`事件 ${e.date} · 報導 ${e.publishedDate} · ${e.time?`${e.time}（臺灣時間）`:"日內時間未詳"}`,'date-note'));if(e.dateNote)card.append(text('p',e.dateNote,'date-note'));$('events').append(card);}
}
function render(){const counties=filtered(),sum=totals(counties);$('county').value=state.county;$('day').value=state.day;$('mapHeading').textContent=state.county==='all'?'全島的日常':`${state.county}的日常`;$('mapDate').textContent=`08 / ${String(state.day).padStart(2,'0')}`;$('dateLabel').textContent=`8 月 ${state.day} 日`;$('dayLabel').textContent=`08 月 ${String(state.day).padStart(2,'0')} 日・模擬日分布`;$('birthTotal').textContent=sum.missing.births?'資料不完整':format(sum.births);$('deathTotal').textContent=sum.missing.deaths?'資料不完整':format(sum.deaths);$('dailyBirth').textContent=sum.missing.births?'未提供':format(counties.reduce((a,c)=>a+c.dailyBirths[state.day-1],0));$('dailyDeath').textContent=sum.missing.deaths?'未提供':format(counties.reduce((a,c)=>a+c.dailyDeaths[state.day-1],0));
 for(const[k,id]of [['births','birthLayer'],['deaths','deathLayer'],['news','newsLayer']])$(id).checked=state[k];$('reducedMotion').checked=state.reduced;document.body.classList.toggle('reduced-motion',state.reduced);document.documentElement.classList.toggle('reduced-motion',state.reduced);$('play').innerHTML=state.playing?'Ⅱ <span>暫停回放</span>':'▶ <span>播放這個月</span>';$('play').setAttribute('aria-label',state.playing?'暫停月份回放':'播放月份回放');$('play').setAttribute('aria-pressed',String(state.playing));
 for(const b of $('categories').children){b.setAttribute('aria-pressed',String(state.categories.includes(b.dataset.category)));b.disabled=!state.news;}
 for(const path of $('countyPaths').querySelectorAll('.county')){path.classList.toggle('selected',path.dataset.county===state.county);path.classList.toggle('dimmed',state.county!=='all'&&path.dataset.county!==state.county);path.setAttribute('aria-pressed',String(path.dataset.county===state.county));}
 const events=currentEvents();renderMarkers(events);renderEvents(events);const daily=Array.from({length:31},(_,i)=>counties.reduce((a,c)=>a+(state.births?c.dailyBirths?.[i]||0:0)+(state.deaths?c.dailyDeaths?.[i]||0:0),0)),max=Math.max(1,...daily);$('dayBars').replaceChildren();daily.forEach((n,i)=>{const bar=document.createElement('i');bar.style.height=`${3+n/max*33}px`;if(i<state.day)bar.classList.add('active');if(events.some(e=>Number(e.date.slice(-2))===i+1))bar.classList.add('news-day');$('dayBars').append(bar);});renderParticles(0);
}
function renderParticles(t){for(const p of particles){const visible=state[p.type]&&(state.county==='all'||p.county===state.county);p.circle.style.display=visible?'':'none';if(!visible)continue;const phase=state.reduced||!state.playing?p.phase:t/1800+p.phase;p.circle.setAttribute('opacity',(.35+.55*(Math.sin(phase)+1)/2).toFixed(2));p.circle.setAttribute('r',(p.r+(state.reduced?0:Math.sin(phase)*.6)).toFixed(2));}}
function tick(time){const delta=last?Math.min(time-last,250):0;last=time;if(state.playing&&!document.hidden){elapsed+=delta;renderParticles(time);const interval=6000/state.speed;if(elapsed>=interval){elapsed=0;if(state.day<31){state.day++;render();}else{state.playing=false;saveURL();render();announce('八月回放完畢。謝謝你一起看見這些日常。');}}}requestAnimationFrame(tick);}
function wire(){for(const c of population.counties){const o=text('option',c.name);o.value=c.name;$('county').append(o);}for(const[k,label]of Object.entries(CATEGORIES)){const b=text('button',label);b.dataset.category=k;b.setAttribute('aria-pressed','true');b.onclick=()=>{state.categories=state.categories.includes(k)?state.categories.filter(x=>x!==k):[...state.categories,k];saveURL();render();};$('categories').append(b);}
 $('county').onchange=e=>{state.county=e.target.value;saveURL();render();};$('day').oninput=e=>{state.day=Number(e.target.value);state.playing=false;elapsed=0;render();};$('day').onchange=saveURL;$('play').onclick=()=>{if(state.day===31&&!state.playing)state.day=1;state.playing=!state.playing;elapsed=0;saveURL();render();};$('speed').onchange=e=>state.speed=Number(e.target.value);for(const[k,id]of [['births','birthLayer'],['deaths','deathLayer'],['news','newsLayer']])$(id).onchange=e=>{state[k]=e.target.checked;saveURL();render();};$('reducedMotion').onchange=e=>{state.reduced=e.target.checked;state.playing=false;render();};$('reset').onclick=()=>{Object.assign(state,{day:1,county:'all',categories:Object.keys(CATEGORIES),births:true,deaths:true,news:true,playing:false});elapsed=0;saveURL();render();announce('已回到月初，重設縣市及所有圖層。');};$('showAll').onclick=()=>{state.day=31;state.playing=false;saveURL();render();};window.onpopstate=()=>{state.playing=false;readURL();render();};matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{state.reduced=e.matches;state.playing=false;render();});document.addEventListener('visibilitychange',()=>{last=0;});
 $('downloadSimulation').onclick=()=>{const rows=[['說明','模擬分布，非真實時間或位置；官方戶籍登記月總數，非實際發生日'],['種子',SEED],['時區','Asia/Taipei'],['日期','縣市','模擬出生登記分配','模擬死亡登記分配','模擬註記']];for(const c of simulation)for(let d=1;d<=31;d++)rows.push([`2026-08-${String(d).padStart(2,'0')}`,c.name,c.dailyBirths?.[d-1]??'',c.dailyDeaths?.[d-1]??'',SIMULATION_LABEL]);const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='SIMULATED-registration-distribution-2026-08.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('monthReason').textContent='本版選擇可完整核對縣市表、全國公告及村里彙總的 2026 年 8 月。9 月村里資料已出現，但本版未與縣市公告完成交叉核對，因此所有資料一致使用 8 月。查核截止：2026-10-06；不自動更新。';for(const s of population.sources){const p=text('p','');p.append(link(`${s.publisher}｜${s.title}`,s.url));$('populationSources').append(p);}const credit=text('p',population.methodology.attribution);$('populationSources').append(credit);$('mapSource').append(text('p','地圖：內政部國土測繪中心「直轄市、縣市界線」COUNTY_MOI_1090820，實際圖資版本 2020-08-20。此開放資料依政府資料開放授權條款第 1 版釋出，圖形已簡化。'),link('官方圖資', 'https://data.gov.tw/dataset/7442'),text('span',' · '),link('政府資料開放授權條款第 1 版','https://data.gov.tw/license'));
}
async function load(){try{[population,geometry,eventData]=await Promise.all(['population','counties-map','events'].map(async name=>{const r=await fetch(`data/${name}.json`);if(!r.ok)throw Error(`${name}: HTTP ${r.status}`);return r.json();}));if(population.month!=='2026-08'||eventData.month!=='2026-08'||population.counties.length!==22||geometry.features.length!==22)throw Error('Data coverage mismatch');validateEvents(eventData.events,'2026-08',population.counties.map(c=>c.name));simulation=createSimulation(population.counties);wire();readURL();buildMap();render();$('loading').hidden=true;$('play').disabled=false;requestAnimationFrame(tick);}catch(error){$('loading').textContent='資料未能完整載入。請重新整理，或由下方下載原始資料。';$('events').textContent='資料載入未完成，沒有顯示部分資料或以零補值。';console.error(error);}}
load();
