import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{distribute,createSimulation,totals,filterEvents,validateEvents,sumToDay,normalizeDay}from'../simulation.js';
const read=n=>JSON.parse(fs.readFileSync(new URL('../data/'+n,import.meta.url))),p=read('population.json'),g=read('counties-map.json'),e=read('events.json'),s=createSimulation(p.counties);
test('official coverage is 22 unique counties, consistent same month and complete',()=>{assert.equal(p.month,e.month);assert.equal(p.month,'2026-08');assert.equal(p.counties.length,22);assert.equal(new Set(p.counties.map(c=>c.name)).size,22);assert.deepEqual(new Set(p.counties.map(c=>c.name)),new Set(g.features.map(f=>f.name)));for(const c of p.counties){assert(Number.isSafeInteger(c.births)&&c.births>=0);assert(Number.isSafeInteger(c.deaths)&&c.deaths>=0);}});
test('national counts and all county monthly simulated totals conserved',()=>{assert.equal(totals(s).births,7492);assert.equal(totals(s).deaths,16470);for(const c of s){assert.equal(c.dailyBirths.length,31);assert.equal(c.dailyDeaths.length,31);assert.equal(sumToDay(c.dailyBirths,31),c.births);assert.equal(sumToDay(c.dailyDeaths,31),c.deaths);assert(c.dailyBirths.every(Number.isInteger));}});
test('fixed seed reproducible and county/type independent',()=>{assert.deepEqual(createSimulation(p.counties),s);assert.notDeepEqual(distribute(100,'A','births'),distribute(100,'B','births'));assert.notDeepEqual(distribute(100,'A','births'),distribute(100,'A','deaths'));});
test('null remains missing; zero is valid; reject invalid counts',()=>{assert.equal(distribute(null,'A','births'),null);assert.equal(sumToDay(null,31),null);assert.deepEqual(distribute(0,'A','births'),Array(31).fill(0));assert.throws(()=>distribute(-1,'A','births'));assert.throws(()=>distribute(3.2,'A','births'));});
test('all daily accumulation is monotonic, month endpoints exact',()=>{for(const c of s)for(const key of ['dailyBirths','dailyDeaths']){let prev=0;for(let d=0;d<=31;d++){const n=sumToDay(c[key],d);assert(n>=prev);prev=n;}assert.equal(sumToDay(c[key],0),0);}});
test('verified event schema, dedup, explicit real dates and unknown time',()=>{assert(validateEvents(e.events));assert.equal(e.events.length,16);assert.equal(new Set(e.events.map(x=>x.url)).size,16);for(const item of e.events){assert(p.counties.some(c=>c.name===item.county));assert.equal(item.locationPrecision,'county');assert(item.publishedDate>=item.date);assert(item.dateNote);assert(item.summary.length<200);}assert.equal(e.events.filter(e=>e.time===null).length,14);});
test('date-only filtering avoids UTC shifts and includes last day',()=>{const cats=['culture','community','nature','rescue','accident','violence'];assert.equal(filterEvents(e.events,{categories:cats,day:31}).length,16);assert.equal(filterEvents(e.events,{categories:cats,day:1}).length,1);assert.equal(filterEvents(e.events,{categories:[],day:31}).length,0);assert.equal(filterEvents(e.events,{categories:cats,county:'連江縣',day:31}).length,0);assert.equal(filterEvents(e.events,{categories:cats,county:'澎湖縣',day:1}).length,1);});
test('real news does not mutate life totals',()=>{const before=JSON.stringify(totals(s));filterEvents(e.events,{categories:['violence'],day:31});assert.equal(JSON.stringify(totals(s)),before);});
test('valid geometric paths, offshore insets and no fabricated fallback',()=>{for(const f of g.features){assert(f.path.startsWith('M'));assert(f.anchor.length===2&&f.anchor.every(Number.isFinite));}assert.deepEqual(new Set(g.insets.map(i=>i.name)),new Set(['連江縣','澎湖縣','金門縣']));assert(g.insets.find(i=>i.name==='金門縣').subInsets.some(i=>i.name==='烏坵'));});
test('UI contains simulation, historical, accessibility and privacy disclosures',()=>{const h=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');for(const term of ['模擬分布，非真實時間或位置','非即時監測','不以 0 取代','犯罪率','Asia/Taipei','減少動態','非精確事故點'])assert(h.includes(term),term);assert(h.includes('type="range"'));assert(h.includes('aria-live="polite"'));});

test('URL day values normalize safely to integer calendar days',()=>{for(const [input,result]of [['1.5',1],['12.9',12],['-5',1],['99',31],['Infinity',1],['abc',1],[null,1]])assert.equal(normalizeDay(input),result);});

test('county enclaves and particle clipping use evenodd polygon fill rules',()=>{const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');assert(app.includes("d:f.path,'fill-rule':'evenodd',class:'county'"));assert(app.includes("d:f.path,'fill-rule':'evenodd','clip-rule':'evenodd'"));});

test('news validation rejects impossible dates, missing hosts, unknown categories and county',()=>{const e0=e.events[0];for(const patch of [{date:'2026-08-99'},{url:'https://'},{category:'made-up'},{county:'不存在'}])assert.throws(()=>validateEvents([{...e0,...patch}],'2026-08',p.counties.map(c=>c.name)));});
